#!/usr/bin/env bash
set -x
set -e

export RAILS_ENV=production

if ! bundle exec rake db:migrate; then
  bundle exec rake db:setup
  bundle exec rake db:migrate
fi
bundle exec rake assets:precompile

[ -f /conf/local_config.rb ] && ln -vsf /conf/local_config.rb ./config/local_config.rb

exec bundle exec unicorn
